services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  motoserver:
    image: ghcr.io/getmoto/motoserver:latest
    ports:
      - 5000:5000
    healthcheck:
      test: curl --fail localhost:5000 || exit 1
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

  sentinela-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: sentinela_dev
      args:
        SENTINELA_PLUGINS: aws,slack
    image: sentinela-dev:latest
    ports:
      - 8000:8000
    environment:
      SENTINELA_PLUGINS: aws,slack
      SAMPLE_SLACK_CHANNEL: C07NCL94SDT
      SAMPLE_SLACK_MENTION: U07NFGGMB98
      SLACK_WEBSOCKET_ENABLED: true
      SLACK_MAIN_CHANNEL: C07NCL94SDT
      SLACK_MAIN_MENTION: U07NFGGMB98
    env_file:
      - .env.secrets
    volumes:
      - .:/app:Z
      # Paths that won't be synced with the container
      - /app/src/_monitors
      - /app/src/_monitors_load
      - /app/src/tmp
    depends_on:
      - postgres
      - motoserver
    command: python3 src/main.py controller executor
