services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      start_period: 5s
      interval: 2s
      timeout: 5s
      retries: 5

  simple-queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: sentinela
      args:
        CONFIGS_FILE: configs/configs-scalable.yaml
    image: sentinela-scalable:latest
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 30M
    ports:
      - 5000:5000
    healthcheck:
      test: health_check 5000
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 2s
    command: python -m simple_queue.simple_queue

  sentinela-controller:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: sentinela
      args:
        CONFIGS_FILE: configs/configs-scalable.yaml
    image: sentinela-scalable:latest
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 100M
    ports:
      - 8000:8000
    healthcheck:
      test: health_check 8000
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 2s
    environment:
      CONFIGS_FILE: configs/configs-scalable.yaml
      EXAMPLE_SLACK_CHANNEL: C07NCL94SDT
      EXAMPLE_SLACK_MENTION: U07NFGGMB98
      SLACK_WEBSOCKET_ENABLED: true
      SLACK_MAIN_CHANNEL: C07NCL94SDT
      SLACK_MAIN_MENTION: U07NFGGMB98
    env_file:
      - .env.secrets
    depends_on:
      postgres:
        condition: service_healthy
      simple-queue:
        condition: service_healthy
    command: sentinela run controller

  sentinela-executor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: sentinela
      args:
        CONFIGS_FILE: configs/configs-scalable.yaml
    image: sentinela-scalable:latest
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: 1
          memory: 128M
    ports:
      - 8001-8100:8000
    healthcheck:
      test: health_check 8000
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 2s
    environment:
      CONFIGS_FILE: configs/configs-scalable.yaml
      EXAMPLE_SLACK_CHANNEL: C07NCL94SDT
      EXAMPLE_SLACK_MENTION: U07NFGGMB98
      SLACK_WEBSOCKET_ENABLED: true
      SLACK_MAIN_CHANNEL: C07NCL94SDT
      SLACK_MAIN_MENTION: U07NFGGMB98
    env_file:
      - .env.secrets
    depends_on:
      postgres:
        condition: service_healthy
      simple-queue:
        condition: service_healthy
    command: sentinela run executor
