services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  sentinela-local:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: sentinela
      args:
        CONFIGS_FILE: configs/configs.yaml
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 128M
    image: sentinela-local:latest
    ports:
      - 8000:8000
    healthcheck:
      test: health_check 8000
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 2s
    env_file:
      - .env.general
      - .env.secrets
    depends_on:
      - postgres
    command: sentinela run controller executor
