from typing import Any, Protocol, runtime_checkable


class Message(Protocol):  # pragma: no cover
    id: str

    @property
    def content(self) -> dict[str, Any]: ...


@runtime_checkable
class Queue(Protocol):  # pragma: no cover
    def __init__(self, config: dict[str, Any]) -> None: ...

    @property
    def queue_wait_message_time(self) -> float: ...

    async def init(self) -> None: ...

    async def send_message(self, type: str, payload: dict[str, Any]) -> None: ...

    async def get_message(self) -> Message | None: ...

    async def change_visibility(self, message: Message) -> None: ...

    async def delete_message(self, message: Message) -> None: ...
